/** Declaration file generated by dts-gen */

export function dump(obj: any, pretty?: boolean): any;

export function parse(text: string): any;

export function stringify(obj: any, pretty?: boolean): any;

export namespace dump {
    const prototype: {
    };

}

export namespace parse {
    const prototype: {
    };

}

export namespace stringify {
    const prototype: {
    };

}

